### ISSUE TITLE
Releasing version 1

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/idiomatch#17]
## To-do's
- [x] change the name of the repo from `identify-idioms` -> `idiomatch` first
- [x] create dist 
- [x] upload with `twine`
- [x] merge to main
- [x]  유저가 모델을 별도로 다운받도록 하기.
- [ ] 이제 release 정리하기

**Comment by eubinecto** [comment]
## en_core_web_sm을 설치할 수 없음?

그냥 로컬 터미널에서 `pip3 install idiomatch`를 해보았는데, 다음과 같은 오류가 뜬다:
```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
idiomatch depends on en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl 
```

음.. 왜 이런걸까? 물론 저 모델이 PyPI에 바로 호스팅되고 있는 패키지가 아닌 것 맞는데,
나는 [이걸](https://stackoverflow.com/a/53383704) 보고서 그냥 install_requires에 모델을 추가했었다.

아, 근데 다시보니...:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/56193069/126601030-71e2e8aa-fbc8-425b-8430-c10776fc25f1.png">

음.. 저걸 안 읽었었네. 하하..

그럼 뭐 어쩌겠어. 그냥 예전처럼 유저가 `python3 -m spacy download en_core_web_sm`을 하도록 하자.

**Comment by eubinecto** [comment]
## 유저가 모델을 직접 다운로드 받도록 하기

그렇게 수정했고, virtualenv를 만들어서 직접 두 스크립트를 테스트 해봄. 성공적으로 설치 & 실행됨!:
```
eubin@eubinecto Downloads % virtualenv testenv 
created virtual environment CPython3.8.6.final.0-64 in 869ms
  creator CPython3Posix(dest=/Users/eubin/Downloads/testenv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/eubin/Library/Application Support/virtualenv)
    added seed packages: numpy==1.19.5, overrides==3.1.0, pip==20.3.3, pip==21.0.1, setuptools==51.0.0, setuptools==57.0.0, six==1.15.0, termcolor==1.1.0, transitions==0.8.6, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
eubin@eubinecto Downloads % source testenv/bin/activate
(testenv) eubin@eubinecto Downloads % pip3 install idiomatch
Collecting idiomatch
  Using cached idiomatch-1.0.1-py3-none-any.whl
Collecting spacy>=3.0.1
  Using cached spacy-3.1.1-cp38-cp38-macosx_10_9_x86_64.whl (6.0 MB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.5-cp38-cp38-macosx_10_9_x86_64.whl (31 kB)
Collecting tqdm<5.0.0,>=4.38.0
  Using cached tqdm-4.61.2-py2.py3-none-any.whl (76 kB)
Collecting pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4
  Using cached pydantic-1.8.2-cp38-cp38-macosx_10_9_x86_64.whl (2.6 MB)
Collecting blis<0.8.0,>=0.4.0
  Using cached blis-0.7.4-cp38-cp38-macosx_10_9_x86_64.whl (5.8 MB)
Collecting typer<0.4.0,>=0.3.0
  Using cached typer-0.3.2-py3-none-any.whl (21 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.5-cp38-cp38-macosx_10_9_x86_64.whl (105 kB)
Collecting catalogue<2.1.0,>=2.0.4
  Using cached catalogue-2.0.4-py3-none-any.whl (16 kB)
Collecting wasabi<1.1.0,>=0.8.1
  Using cached wasabi-0.8.2-py3-none-any.whl (23 kB)
Collecting spacy-legacy<3.1.0,>=3.0.7
  Using cached spacy_legacy-3.0.8-py2.py3-none-any.whl (14 kB)
Collecting pathy>=0.3.5
  Using cached pathy-0.6.0-py3-none-any.whl (42 kB)
Requirement already satisfied: numpy>=1.15.0 in ./testenv/lib/python3.8/site-packages (from spacy>=3.0.1->idiomatch) (1.19.5)
Collecting packaging>=20.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Requirement already satisfied: setuptools in ./testenv/lib/python3.8/site-packages (from spacy>=3.0.1->idiomatch) (57.0.0)
Collecting srsly<3.0.0,>=2.4.1
  Using cached srsly-2.4.1-cp38-cp38-macosx_10_9_x86_64.whl (450 kB)
Collecting jinja2
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting thinc<8.1.0,>=8.0.8
  Using cached thinc-8.0.8-cp38-cp38-macosx_10_9_x86_64.whl (598 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.5-cp38-cp38-macosx_10_9_x86_64.whl (18 kB)
Collecting requests<3.0.0,>=2.13.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting smart-open<6.0.0,>=5.0.0
  Using cached smart_open-5.1.0-py3-none-any.whl (57 kB)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.3-py3-none-any.whl (35 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting click<7.2.0,>=7.1.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp38-cp38-macosx_10_9_x86_64.whl (13 kB)
Installing collected packages: typing-extensions, murmurhash, cymem, click, catalogue, wasabi, urllib3, typer, srsly, smart-open, pyparsing, pydantic, preshed, MarkupSafe, idna, charset-normalizer, certifi, blis, tqdm, thinc, spacy-legacy, requests, pathy, packaging, jinja2, spacy, idiomatch
Successfully installed MarkupSafe-2.0.1 blis-0.7.4 catalogue-2.0.4 certifi-2021.5.30 charset-normalizer-2.0.3 click-7.1.2 cymem-2.0.5 idiomatch-1.0.1 idna-3.2 jinja2-3.0.1 murmurhash-1.0.5 packaging-21.0 pathy-0.6.0 preshed-3.0.5 pydantic-1.8.2 pyparsing-2.4.7 requests-2.26.0 smart-open-5.1.0 spacy-3.1.1 spacy-legacy-3.0.8 srsly-2.4.1 thinc-8.0.8 tqdm-4.61.2 typer-0.3.2 typing-extensions-3.10.0.0 urllib3-1.26.6 wasabi-0.8.2
WARNING: You are using pip version 21.0.1; however, version 21.1.3 is available.
You should consider upgrading via the '/Users/eubin/Downloads/testenv/bin/python -m pip install --upgrade pip' command.
(testenv) eubin@eubinecto Downloads % python3 -m spacy download en_core_web_sm
Collecting en-core-web-sm==3.1.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl (13.6 MB)
     |████████████████████████████████| 13.6 MB 2.2 MB/s 
Requirement already satisfied: spacy<3.2.0,>=3.1.0 in ./testenv/lib/python3.8/site-packages (from en-core-web-sm==3.1.0) (3.1.1)
Requirement already satisfied: numpy>=1.15.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (1.19.5)
Requirement already satisfied: setuptools in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (57.0.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (3.0.5)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (0.7.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.7 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (3.0.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.4 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.0.4)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.4.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (4.61.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.26.0)
Requirement already satisfied: jinja2 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (3.0.1)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.0.5)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (0.3.2)
Requirement already satisfied: packaging>=20.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (21.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (1.8.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (1.0.5)
Requirement already satisfied: thinc<8.1.0,>=8.0.8 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (8.0.8)
Requirement already satisfied: pathy>=0.3.5 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (0.6.0)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in ./testenv/lib/python3.8/site-packages (from spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (0.8.2)
Requirement already satisfied: pyparsing>=2.0.2 in ./testenv/lib/python3.8/site-packages (from packaging>=20.0->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.4.7)
Requirement already satisfied: smart-open<6.0.0,>=5.0.0 in ./testenv/lib/python3.8/site-packages (from pathy>=0.3.5->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (5.1.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./testenv/lib/python3.8/site-packages (from pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (3.10.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./testenv/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (1.26.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./testenv/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.0.3)
Requirement already satisfied: idna<4,>=2.5 in ./testenv/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in ./testenv/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2021.5.30)
Requirement already satisfied: click<7.2.0,>=7.1.1 in ./testenv/lib/python3.8/site-packages (from typer<0.4.0,>=0.3.0->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (7.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./testenv/lib/python3.8/site-packages (from jinja2->spacy<3.2.0,>=3.1.0->en-core-web-sm==3.1.0) (2.0.1)
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.1.0
WARNING: You are using pip version 21.0.1; however, version 21.1.3 is available.
You should consider upgrading via the '/Users/eubin/Downloads/testenv/bin/python3 -m pip install --upgrade pip' command.
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
(testenv) eubin@eubinecto Downloads % python3 
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from idiomatch import Idiomatcher
>>> import spacy
>>> nlp = spacy.load("en_core_web_sm")
>>> idomatcher = Idiomatcher.from_pretrained(nlp)
adding patterns into idiomatcher...: 100%|████████████████████████████████████████████████████| 2756/2756 [01:00<00:00, 45.30it/s]
>>> idomatcher.identify(nlp("Don't beat around the bush!"))
[{'idiom': 'beat around the bush', 'span': 'beat around the bush', 'meta': (368504932656763830, 2, 6)}]
>>> idomatcher.identify(nlp("You will have her blood on your hands"))
[{'idiom': "have blood on one's hands", 'span': 'have her blood on your hands', 'meta': (5930902300252675198, 2, 8)}, {'idiom': "on one's hands", 'span': 'on your hands', 'meta': (8246625119345375174, 5, 8)}]
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit

```

**Comment by eubinecto** [comment]
## 릴리즈 1.0.1 정리하기
